name = "SplendorSA"
uuid = "591cf800-d8b7-4f1b-a472-0256720356de"
authors = ["Daniel Boigk"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
